-- --------------------------------------------------------
-- Servidor:                     192.168.255.128
-- Versão do servidor:           5.7.16 - MySQL Community Server (GPL)
-- OS do Servidor:               Linux
-- HeidiSQL Versão:              9.3.0.4984
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Copiando estrutura do banco de dados para NoteFood
CREATE DATABASE IF NOT EXISTS `NoteFood` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `NoteFood`;


-- Copiando estrutura para tabela NoteFood.ALIMENTO
CREATE TABLE IF NOT EXISTS `ALIMENTO` (
  `ALIMENTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NOME` varchar(45) NOT NULL,
  `DESCRICAO` varchar(100) NOT NULL,
  `SUB_GRUPO_SUB_GRUPO_ID` int(10) unsigned NOT NULL,
  PRIMARY KEY (`ALIMENTO_ID`),
  UNIQUE KEY `ALIMENTO_ID_UNIQUE` (`ALIMENTO_ID`),
  KEY `fk_ALIMENTO_SUB_GRUPO1_idx` (`SUB_GRUPO_SUB_GRUPO_ID`),
  CONSTRAINT `fk_ALIMENTO_SUB_GRUPO1` FOREIGN KEY (`SUB_GRUPO_SUB_GRUPO_ID`) REFERENCES `SUB_GRUPO` (`SUB_GRUPO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

-- Copiando dados para a tabela NoteFood.ALIMENTO: ~2 rows (aproximadamente)
/*!40000 ALTER TABLE `ALIMENTO` DISABLE KEYS */;
INSERT INTO `ALIMENTO` (`ALIMENTO_ID`, `NOME`, `DESCRICAO`, `SUB_GRUPO_SUB_GRUPO_ID`) VALUES
	(1, 'Macarrão', 'Italiano!!!', 1),
	(2, 'Arroz', 'Comida dos Japas', 1);
/*!40000 ALTER TABLE `ALIMENTO` ENABLE KEYS */;


-- Copiando estrutura para tabela NoteFood.ALIMENTO_SELECIONADO
CREATE TABLE IF NOT EXISTS `ALIMENTO_SELECIONADO` (
  `ALIMENTO_SELECIONADO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ALIMENTO_ID` int(10) unsigned NOT NULL,
  `QTD` int(11) NOT NULL,
  PRIMARY KEY (`ALIMENTO_SELECIONADO_ID`),
  KEY `FK_ALIMENTO_SELECIONADO_ALIMENTO` (`ALIMENTO_ID`),
  CONSTRAINT `FK_ALIMENTO_SELECIONADO_ALIMENTO` FOREIGN KEY (`ALIMENTO_ID`) REFERENCES `ALIMENTO` (`ALIMENTO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

-- Copiando dados para a tabela NoteFood.ALIMENTO_SELECIONADO: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ALIMENTO_SELECIONADO` DISABLE KEYS */;
INSERT INTO `ALIMENTO_SELECIONADO` (`ALIMENTO_SELECIONADO_ID`, `ALIMENTO_ID`, `QTD`) VALUES
	(3, 1, 1);
/*!40000 ALTER TABLE `ALIMENTO_SELECIONADO` ENABLE KEYS */;


-- Copiando estrutura para tabela NoteFood.CONSTRUTOR
CREATE TABLE IF NOT EXISTS `CONSTRUTOR` (
  `ALIMENTO_ALIMENTO_ID` int(10) unsigned NOT NULL,
  `Qt_Proteina` float NOT NULL,
  `Qt_Caloria` float NOT NULL,
  PRIMARY KEY (`ALIMENTO_ALIMENTO_ID`),
  CONSTRAINT `fk_CONSTRUTOR_ALIMENTO1` FOREIGN KEY (`ALIMENTO_ALIMENTO_ID`) REFERENCES `ALIMENTO` (`ALIMENTO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Copiando dados para a tabela NoteFood.CONSTRUTOR: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `CONSTRUTOR` DISABLE KEYS */;
/*!40000 ALTER TABLE `CONSTRUTOR` ENABLE KEYS */;


-- Copiando estrutura para tabela NoteFood.DIETA
CREATE TABLE IF NOT EXISTS `DIETA` (
  `DIETA_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Qt_Refeicao` int(10) unsigned NOT NULL,
  `USUARIO_USUARIO_ID` int(10) unsigned NOT NULL,
  PRIMARY KEY (`DIETA_ID`),
  UNIQUE KEY `idDIETA_UNIQUE` (`DIETA_ID`),
  KEY `fk_DIETA_USUARIO_idx` (`USUARIO_USUARIO_ID`),
  CONSTRAINT `fk_DIETA_USUARIO` FOREIGN KEY (`USUARIO_USUARIO_ID`) REFERENCES `USUARIO` (`USUARIO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Copiando dados para a tabela NoteFood.DIETA: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `DIETA` DISABLE KEYS */;
/*!40000 ALTER TABLE `DIETA` ENABLE KEYS */;


-- Copiando estrutura para tabela NoteFood.GRUPO
CREATE TABLE IF NOT EXISTS `GRUPO` (
  `GRUPO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Grupo_Nome` varchar(45) NOT NULL,
  `Nutriente_Principal` varchar(45) NOT NULL,
  `Qt_Diaria_Recomendada` int(11) NOT NULL,
  PRIMARY KEY (`GRUPO_ID`),
  UNIQUE KEY `GRUPO_ID_UNIQUE` (`GRUPO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

-- Copiando dados para a tabela NoteFood.GRUPO: ~1 rows (aproximadamente)
/*!40000 ALTER TABLE `GRUPO` DISABLE KEYS */;
INSERT INTO `GRUPO` (`GRUPO_ID`, `Grupo_Nome`, `Nutriente_Principal`, `Qt_Diaria_Recomendada`) VALUES
	(1, 'Energeticos', 'Carboidrato', 1);
/*!40000 ALTER TABLE `GRUPO` ENABLE KEYS */;


-- Copiando estrutura para tabela NoteFood.REFEICAO
CREATE TABLE IF NOT EXISTS `REFEICAO` (
  `Data` varchar(45) NOT NULL,
  `Hora` varchar(45) NOT NULL,
  `DIETA_DIETA_ID` int(10) unsigned NOT NULL,
  KEY `fk_REFEICAO_DIETA1_idx` (`DIETA_DIETA_ID`),
  CONSTRAINT `fk_REFEICAO_DIETA1` FOREIGN KEY (`DIETA_DIETA_ID`) REFERENCES `DIETA` (`DIETA_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Copiando dados para a tabela NoteFood.REFEICAO: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `REFEICAO` DISABLE KEYS */;
/*!40000 ALTER TABLE `REFEICAO` ENABLE KEYS */;


-- Copiando estrutura para tabela NoteFood.REGULADOR
CREATE TABLE IF NOT EXISTS `REGULADOR` (
  `ALIMENTO_ALIMENTO_ID` int(10) unsigned NOT NULL,
  `Qt_Fibra` int(11) NOT NULL,
  `Qt_Caloria` float NOT NULL,
  PRIMARY KEY (`ALIMENTO_ALIMENTO_ID`),
  CONSTRAINT `fk_REGULADOR_ALIMENTO1` FOREIGN KEY (`ALIMENTO_ALIMENTO_ID`) REFERENCES `ALIMENTO` (`ALIMENTO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Copiando dados para a tabela NoteFood.REGULADOR: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `REGULADOR` DISABLE KEYS */;
/*!40000 ALTER TABLE `REGULADOR` ENABLE KEYS */;


-- Copiando estrutura para tabela NoteFood.SUB_GRUPO
CREATE TABLE IF NOT EXISTS `SUB_GRUPO` (
  `SUB_GRUPO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Sub_Grupo_Nome` varchar(45) NOT NULL,
  `GRUPO_GRUPO_ID` int(10) unsigned NOT NULL,
  PRIMARY KEY (`SUB_GRUPO_ID`),
  UNIQUE KEY `SUB_GRUPO_ID_UNIQUE` (`SUB_GRUPO_ID`),
  KEY `fk_SUB_GRUPO_GRUPO1_idx` (`GRUPO_GRUPO_ID`),
  CONSTRAINT `fk_SUB_GRUPO_GRUPO1` FOREIGN KEY (`GRUPO_GRUPO_ID`) REFERENCES `GRUPO` (`GRUPO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

-- Copiando dados para a tabela NoteFood.SUB_GRUPO: ~1 rows (aproximadamente)
/*!40000 ALTER TABLE `SUB_GRUPO` DISABLE KEYS */;
INSERT INTO `SUB_GRUPO` (`SUB_GRUPO_ID`, `Sub_Grupo_Nome`, `GRUPO_GRUPO_ID`) VALUES
	(1, 'Massas', 1);
/*!40000 ALTER TABLE `SUB_GRUPO` ENABLE KEYS */;


-- Copiando estrutura para tabela NoteFood.USUARIO
CREATE TABLE IF NOT EXISTS `USUARIO` (
  `USUARIO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Nome_Usuario` varchar(45) NOT NULL,
  `Email_Usuario` varchar(45) NOT NULL,
  `DataNasc` varchar(45) NOT NULL,
  `Sexo` char(1) NOT NULL,
  `Peso` float unsigned NOT NULL,
  `Altura` float unsigned NOT NULL,
  PRIMARY KEY (`USUARIO_ID`),
  UNIQUE KEY `USUARIO_ID_UNIQUE` (`USUARIO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Copiando dados para a tabela NoteFood.USUARIO: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `USUARIO` DISABLE KEYS */;
/*!40000 ALTER TABLE `USUARIO` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
